## Array Creation

In [1]:
import numpy as np

# full() 
arr1 = np.full((2,3),5) # creates 2*3 array with all values = 5.
print(arr1)
print()

arr2 = np.full((2,3), [3,2,3]) 
print(arr2)
print()

# empty()
arr3 = np.empty((2,3)) # creates Array of uninitialized (arbitrary) data of the given shape,
print(arr3)

[[5 5 5]
 [5 5 5]]

[[3 2 3]
 [3 2 3]]

[[6.23061763e-307 6.23059386e-307 1.50201822e-307]
 [4.67296746e-307 1.69121096e-306 1.29061821e-306]]


## Working with CSV files

In [4]:
# loading csv file
arr1 = np.genfromtxt('files\\Iris.csv', delimiter=',')
print(arr1[:10])
print()


# loading only float values
arr2 = np.genfromtxt('files\\Iris.csv', delimiter=',',dtype='str' )
print(arr2[:5])

arr3 = np.array(arr2[1:,:5]).astype(float) # remove csv header and string columns
print(arr3[:5])
print()


# to work with csv headers, use names = True
arr4 = np.genfromtxt('files\\Iris.csv', delimiter=',', names = True)
print(arr4['Id'][:10])

[[nan nan nan nan nan nan]
 [1.  5.1 3.5 1.4 0.2 nan]
 [2.  4.9 3.  1.4 0.2 nan]
 [3.  4.7 3.2 1.3 0.2 nan]
 [4.  4.6 3.1 1.5 0.2 nan]
 [5.  5.  3.6 1.4 0.2 nan]
 [6.  5.4 3.9 1.7 0.4 nan]
 [7.  4.6 3.4 1.4 0.3 nan]
 [8.  5.  3.4 1.5 0.2 nan]
 [9.  4.4 2.9 1.4 0.2 nan]]

[['Id' 'SepalLengthCm' 'SepalWidthCm' 'PetalLengthCm' 'PetalWidthCm'
  'Species']
 ['1' '5.1' '3.5' '1.4' '0.2' 'Iris-setosa']
 ['2' '4.9' '3.0' '1.4' '0.2' 'Iris-setosa']
 ['3' '4.7' '3.2' '1.3' '0.2' 'Iris-setosa']
 ['4' '4.6' '3.1' '1.5' '0.2' 'Iris-setosa']]
[[1.  5.1 3.5 1.4 0.2]
 [2.  4.9 3.  1.4 0.2]
 [3.  4.7 3.2 1.3 0.2]
 [4.  4.6 3.1 1.5 0.2]
 [5.  5.  3.6 1.4 0.2]]

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


## saving numpy array as txt or csv

In [ ]:
# saving a numpy array as txt file
np.savetxt("arr4.txt", arr4, delimiter=' ')
# change extension to .csv and delimeter to ',' for saving as csv
np.savetxt("arr4.csv", arr4, delimiter=',')

## Sorting array

In [ ]:
# sort() function return None. it sorts inplace
arr3.sort()
print(arr3[:5]) # by default sort by innermost axis, (here by columns of a row).
print()

arr3.sort(axis = 0) # sort by rows
print(arr3[:5])


[[0.2 1.  1.4 3.5 5.1]
 [0.2 1.4 2.  3.  4.9]
 [0.2 1.3 3.  3.2 4.7]
 [0.2 1.5 3.1 4.  4.6]
 [0.2 1.4 3.6 5.  5. ]]

[[0.1 1.  1.4 3.  4.6]
 [0.1 1.  2.  3.2 4.7]
 [0.1 1.1 2.3 3.5 4.9]
 [0.1 1.2 2.9 4.  5. ]
 [0.1 1.2 3.  4.3 5.1]]
