# Data Preprocessing Part 2


In [5]:
import pandas
import scipy
import numpy
from sklearn.preprocessing import MinMaxScaler

path = r"C:\Users\Home\jupyter works\CSV\winequality-red.csv"
dataframe = pandas.read_csv(path,sep=';')
dataframe

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   
5            7.4              0.66         0.00             1.8      0.075   
6            7.9              0.60         0.06             1.6      0.069   
7            7.3              0.65         0.00             1.2      0.065   
8            7.8              0.58         0.02             2.0      0.073   
9            7.5              0.50         0.36             6.1      0.071   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                   11                    34   0.9978  3.51       0.56   
1                   25                    67   0.9968  3.20       0.68   
2                   15                    54   0.9970  3.26       0.65   
3                   17                    60   0.9980  3.16       0.58   
4                   11                    34   0.9978  3.51       0.56   
5                   13                    40   0.9978  3.51       0.56   
6                   15                    59   0.9964  3.30       0.46   
7                   15                    21   0.9946  3.39       0.47   
8                    9                    18   0.9968  3.36       0.57   
9                   17                   102   0.9978  3.35       0.80   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5  
5      9.4        5  
6      9.4        5  
7     10.0        7  
8      9.5        7  
9     10.5        5

### Scaling Features in a range (0,1)

In [26]:
df_array = dataframe.values
# separating independent(x) and dependent(y)
x = df_array[:,0:11]
y = df_array[:,11]

scaler = MinMaxScaler(feature_range=(0,1))
rescaledX = scaler.fit_transform(x)
numpy.set_printoptions(precision=3) #setting precision for array output
print(rescaledX)


[[0.026 0.7   0.    0.143 0.333 0.125 0.19  0.941 1.    0.294 0.   ]
 [0.128 1.    0.    0.286 1.    1.    0.583 0.647 0.114 0.647 0.364]
 [0.128 0.8   0.071 0.224 0.818 0.375 0.429 0.706 0.286 0.559 0.364]
 [1.    0.    1.    0.143 0.303 0.5   0.5   1.    0.    0.353 0.364]
 [0.026 0.7   0.    0.143 0.333 0.125 0.19  0.941 1.    0.294 0.   ]
 [0.026 0.633 0.    0.122 0.303 0.25  0.262 0.941 1.    0.294 0.   ]
 [0.154 0.533 0.107 0.082 0.121 0.375 0.488 0.529 0.4   0.    0.   ]
 [0.    0.617 0.    0.    0.    0.375 0.036 0.    0.657 0.029 0.545]
 [0.128 0.5   0.036 0.163 0.242 0.    0.    0.647 0.571 0.324 0.091]
 [0.051 0.367 0.643 1.    0.182 0.5   1.    0.941 0.543 1.    1.   ]]


### Standardizing Data

In [12]:

from sklearn.preprocessing import StandardScaler
rescaledX = StandardScaler().fit_transform(x)
rescaledX

array([[-0.499,  0.452, -0.563, -0.329, -0.103, -0.897, -0.627,  0.731],
       [-0.136,  1.63 , -0.563,  0.207,  2.171,  2.407,  0.761, -0.284],
       [-0.136,  0.845, -0.347, -0.023,  1.55 ,  0.047,  0.214, -0.081],
       [ 2.947, -2.298,  2.471, -0.329, -0.207,  0.519,  0.467,  0.934],
       [-0.499,  0.452, -0.563, -0.329, -0.103, -0.897, -0.627,  0.731],
       [-0.499,  0.19 , -0.563, -0.406, -0.207, -0.425, -0.374,  0.731],
       [-0.045, -0.203, -0.238, -0.559, -0.827,  0.047,  0.425, -0.691],
       [-0.589,  0.124, -0.563, -0.866, -1.24 ,  0.047, -1.173, -2.519],
       [-0.136, -0.334, -0.455, -0.253, -0.413, -1.369, -1.299, -0.284],
       [-0.408, -0.858,  1.387,  2.888, -0.62 ,  0.519,  2.233,  0.731]])

### Binarizing Data
all values greater than threshold are transformed into 1 and less than into 0

this method is used when we deal with probablities and have to convert data into crisp values.


In [13]:
from sklearn.preprocessing import Binarizer
binarizer = Binarizer(threshold=0.0).fit(x)
binary_X = binarizer.transform(x)
binary_X

array([[1., 1., 0., 1., 1., 1., 1., 1.],
       [1., 1., 0., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 0., 1., 1., 1., 1., 1.],
       [1., 1., 0., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 0., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

### Label and One Hot Encoding


In [64]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
print(y)
# Label Encoding
lbl_Y = LabelEncoder().fit_transform(y)
print(lbl_Y)


# One HOt Encoding
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([('encoder',OneHotEncoder(),[11])],remainder='passthrough')
oht_Y = ct.fit_transform(dataframe)  # we are using the whole dataframe
print(oht_Y[:,0:3]) # result always get attached to first columns of dataframe.


# this is just an example. one hot encoding is never performed over the output or the dependent variable.

[5. 5. 5. 6. 5. 5. 5. 7. 7. 5.]
[0 0 0 1 0 0 0 2 2 0]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]]
